server {
    listen 80;
    server_name _;
    client_max_body_size 2g;
    access_log off;
    error_log /var/log/nginx/error.log warn;

    location /api/static/ {
        proxy_pass http://backend:8002/static/;
    }

    location /api/ {
        proxy_pass http://backend:8002/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 1800s;
        proxy_send_timeout 1800s;
    }

    location = /docs {
        proxy_pass http://backend:8002/docs;
    }

    location = /openapi.json {
        proxy_pass http://backend:8002/openapi.json;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }
}
